# SelahOS mkinitcpio configuration — LIVE ENVIRONMENT
# USB storage modules added to MODULES to ensure USB drives
# are detected before archiso hook runs.
# Copyright (C) 2026 Selah Technologies LLC

MODULES=(usb_storage uas usbcore xhci_hcd ehci_hcd ohci_hcd)
BINARIES=()
FILES=()
HOOKS=(base udev modconf kms block archiso archiso_loop_mnt archiso_pxe_common archiso_pxe_http archiso_pxe_nfs memdisk filesystems)
COMPRESSION="zstd"
