#!/usr/bin/env python3
"""Generate committed runtime assets. Requires python-pyqt6, QtSvg. No network."""
import argparse
import json
import os
from pathlib import Path
import tempfile

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
from PyQt6.QtGui import QGuiApplication, QImage, QPainter, QColor, QPen
from PyQt6.QtCore import Qt, QRectF
from PyQt6.QtSvg import QSvgRenderer

ROOT = Path(__file__).resolve().parents[1]
app = QGuiApplication([])
tokens = json.loads((ROOT / "design/tokens.json").read_text())

def rgb(value):
    return [int(value[n:n+2], 16) / 255 for n in (1, 3, 5)]

def generate(out):
    def write(name, data):
        dest = out / name
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(data)

    qml = "import QtQuick\n\n// Generated by tools/generate.py; edit design/tokens.json.\nQtObject {\n"
    for key, value in tokens["colors"].items():
        qml += f'    readonly property color {key}: "{value}"\n'
    qml += f'    readonly property string fontFamily: "{tokens["typography"]["family"]}"\n'
    for key, value in tokens["spacing"].items():
        qml += f'    readonly property int space{key.capitalize()}: {value}\n'
    for key, value in tokens["radii"].items():
        qml += f'    readonly property int radius{key.capitalize()}: {value}\n'
    qml += "}\n"
    write("login/selah-sddm/Tokens.qml", qml)

    header = "# Generated palette. See design/tokens.json.\n"
    for prefix, key in [("bg", "background"), ("text", "text"), ("gold", "gold")]:
        for suffix, value in zip("rgb", rgb(tokens["colors"][key])):
            header += f"{prefix}_{suffix} = {value:.6f};\n"
    body = (ROOT / "boot/selah-plymouth/selah.script").read_text()
    for name, motion in [("selah-experience", 1), ("selah-experience-static", 0)]:
        write(f"boot/generated/{name}.script", header + f"motion_enabled = {motion};\n" + body)
        write(f"boot/generated/{name}.plymouth",
              "[Plymouth Theme]\nName=Selah Experience" + (" (static)" if not motion else "") +
              "\nDescription=Pause. Reflect. Create.\nModuleName=script\n\n[script]\n"
              "ImageDir=/usr/share/plymouth/themes/selah-experience/assets\n"
              f"ScriptFile=/usr/share/plymouth/themes/{name}/{name}.script\n")

    assets = out / "boot/selah-plymouth/assets"
    assets.mkdir(parents=True, exist_ok=True)
    logo = QImage(160, 160, QImage.Format.Format_ARGB32_Premultiplied)
    logo.fill(Qt.GlobalColor.transparent)
    painter = QPainter(logo)
    renderer = QSvgRenderer(str(ROOT / "branding/selah-mark.svg"))
    if not renderer.isValid():
        raise SystemExit("Invalid authoritative logo")
    renderer.render(painter, QRectF(0, 0, 160, 160))
    painter.end()
    assert logo.save(str(assets / "logo.png"))
    for i, size in enumerate((192, 224, 256)):
        img = QImage(size, size, QImage.Format.Format_ARGB32_Premultiplied)
        img.fill(Qt.GlobalColor.transparent)
        p = QPainter(img)
        p.setRenderHint(QPainter.RenderHint.Antialiasing)
        p.setPen(QPen(QColor(tokens["colors"]["gold"]), 1.5))
        p.drawEllipse(QRectF(3, 3, size-6, size-6))
        p.end()
        assert img.save(str(assets / f"ring-{i}.png"))
    point = QImage(12, 12, QImage.Format.Format_ARGB32_Premultiplied)
    point.fill(Qt.GlobalColor.transparent)
    p = QPainter(point)
    p.setRenderHint(QPainter.RenderHint.Antialiasing)
    p.setPen(Qt.PenStyle.NoPen)
    p.setBrush(QColor(tokens["colors"]["goldLight"]))
    p.drawEllipse(QRectF(1, 1, 10, 10))
    p.end()
    assert point.save(str(assets / "point.png"))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            generate(target)
            stale = [str(p.relative_to(target)) for p in target.rglob("*") if p.is_file()
                     and (not (ROOT / p.relative_to(target)).is_file()
                          or p.read_bytes() != (ROOT / p.relative_to(target)).read_bytes())]
            if stale:
                raise SystemExit("Regenerate assets: " + ", ".join(stale))
        print("Generated assets match tokens and source.")
    else:
        generate(ROOT)
