import QtQuick

// Generated by tools/generate.py; edit design/tokens.json.
QtObject {
    readonly property color background: "#0D1020"
    readonly property color surface: "#171C2A"
    readonly property color field: "#2A3042"
    readonly property color text: "#FFFFFF"
    readonly property color muted: "#B8BDC9"
    readonly property color gold: "#D6A85A"
    readonly property color goldLight: "#E6C27A"
    readonly property color goldDark: "#BD8B3C"
    readonly property color error: "#E07A5F"
    readonly property color success: "#81B29A"
    readonly property string fontFamily: "Noto Sans"
    readonly property int spaceXs: 4
    readonly property int spaceSm: 8
    readonly property int spaceMd: 12
    readonly property int spaceLg: 16
    readonly property int spaceXl: 24
    readonly property int spaceXxl: 32
    readonly property int spaceSection: 48
    readonly property int radiusField: 8
    readonly property int radiusButton: 10
    readonly property int radiusPanel: 16
}
