#
# /etc/pacman.conf for SelahOS v1.0-beta ISO build
# Copyright (C) 2026 Selah Technologies LLC
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 5
DisableSandbox

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Chaotic-AUR: provides calamares, ckbcomp, dxvk, wineasio
# Keys bootstrapped by build-iso.sh before mkarchiso runs
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist

[selah-local]
SigLevel = Optional TrustAll
Server = file:///home/dbnoble/SelahOS-Dev/selahos-iso-v3/local-repo
