#
# /etc/pacman.conf for SelahOS v1.0-beta ISO build
# Copyright (C) 2026 Selah Technologies LLC
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
SigLevel = Never
LocalFileSigLevel = Never
ParallelDownloads = 5
DisableSandboxFilesystem
DisableSandboxSyscalls

[selah-local]
SigLevel = Never
Server = file:///home/dbnoble/SelahOS-Dev/selahos-iso-v3/local-repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Chaotic-AUR: provides calamares, ckbcomp, dxvk, wineasio
# Keys bootstrapped by build-iso.sh before mkarchiso runs
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
