#!/usr/bin/env bash
# shellcheck disable=SC2034
# SelahOS v2.0.1.1-beta archiso profile
# Copyright (C) 2026 Selah Technologies LLC

iso_name="selahos"
iso_label="SELAHOS_$(date +%Y%m)"
iso_publisher="Selah Technologies LLC <https://selahos.io>"
iso_application="SelahOS Beta 2.0.1.1 — Live and Install Medium"
iso_version="2.0.1.1-beta-$(date +%Y.%m.%d)"
install_dir="arch"
buildmodes=('iso')
bootmodes=(
  'bios.syslinux'
  'uefi.grub'
)
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '6' '-processors' '4' '-mem' '2G')
bootstrap_tarball_compression=('zstd' '-c' '-T0' '--auto-threads=logical' '--long' '-19')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/etc/gshadow"]="0:0:400"
  ["/etc/sddm.conf"]="0:0:644"
  ["/root"]="0:0:750"
  ["/root/customize_airootfs.sh"]="0:0:755"
  ["/etc/sudoers.d/g_wheel"]="0:0:440"
  ["/etc/sudoers.d/liveuser"]="0:0:440"
  ["/etc/mkinitcpio.conf"]="0:0:644"
  ["/etc/mkinitcpio.d/linux-zen.preset"]="0:0:644"
  ["/etc/mkinitcpio.d/linux-lts.preset"]="0:0:644"
  ["/usr/local/bin/selah-rescue"]="0:0:755"
  ["/usr/local/bin/selah-update"]="0:0:755"
  ["/usr/local/bin/selah-ai-detect"]="0:0:755"
  ["/usr/local/bin/selah-ai-setup"]="0:0:755"
  ["/usr/local/bin/selahos-welcome"]="0:0:755"
  ["/usr/local/bin/selahos-firstrun-notice"]="0:0:755"
  ["/usr/local/bin/selahos-calamares-launcher"]="0:0:755"
  ["/usr/local/bin/selahos-memory-info"]="0:0:755"
  ["/usr/local/bin/selahos-hardware-detect"]="0:0:755"
  ["/usr/local/bin/selahos-installer"]="0:0:755"
  ["/usr/local/bin/selahos-installer-launcher"]="0:0:755"
  ["/usr/local/bin/selah-setup"]="0:0:755"
  ["/usr/local/bin/selah-print"]="0:0:755"
  ["/usr/local/bin/selahos-print-center"]="0:0:755"
  ["/usr/local/bin/selah-about"]="0:0:755"
  ["/usr/local/bin/selah-recover"]="0:0:755"
  ["/usr/local/bin/selahos-recovery-center"]="0:0:755"
  ["/usr/local/bin/selah-asio-config"]="0:0:755"
  ["/usr/local/bin/selah-audio-fix"]="0:0:755"
  ["/usr/local/bin/selahauth"]="0:0:755"
  ["/usr/local/bin/selahbridge-detect"]="0:0:755"
  ["/usr/local/bin/selah-bridgepro-selftest"]="0:0:755"
  ["/usr/share/selahbridgepro/selftest/selahbridge-selftest.exe"]="0:0:755"
  ["/usr/local/bin/selahbridge-install"]="0:0:755"
  ["/usr/local/bin/selahbridge-sandbox"]="0:0:755"
  ["/usr/local/bin/selahbridge-winapp"]="0:0:755"
  ["/usr/local/bin/selahbridgepro"]="0:0:755"
  ["/usr/local/bin/selah-mpc-bridge"]="0:0:755"
  ["/usr/local/bin/selah-mpc-led"]="0:0:755"
  ["/usr/local/bin/selah-mpc-snoop"]="0:0:755"
  ["/usr/local/bin/selah-mpk-mini-iv"]="0:0:755"
  ["/usr/local/bin/selahpro"]="0:0:755"
  ["/usr/local/bin/selahseedcore-init"]="0:0:755"
  ["/usr/local/bin/selah-seedcore-reapply"]="0:0:755"
  ["/usr/local/bin/selahwine"]="0:0:755"
  ["/usr/local/bin/selah-wifi-driver"]="0:0:755"
  ["/usr/local/bin/selah-repair"]="0:0:755"
  ["/usr/local/bin/selah-clamshell"]="0:0:755"
  ["/usr/local/bin/selahos-device-editors"]="0:0:755"
  ["/usr/local/bin/selah-preflight-check"]="0:0:755"
  ["/usr/local/bin/selah-postflight-check"]="0:0:755"
  ["/usr/local/bin/selah-doctor"]="0:0:755"
  ["/usr/local/lib/selahos/device-bridge/selahos-device-editors"]="0:0:755"
  ["/usr/local/lib/selahos/device-bridge/lib/auto-init.sh"]="0:0:755"
  ["/usr/local/lib/selahos/device-bridge/lib/udev-init.sh"]="0:0:755"
  ["/usr/lib/systemd/system-sleep/bluetooth-resume"]="0:0:755"
  ["/usr/lib/systemd/system-sleep/selah-display-resume"]="0:0:755"
  ["/usr/lib/systemd/system-sleep/selah-wifi-resume"]="0:0:755"
  ["/usr/share/selahos/hardware-db.json"]="0:0:644"
)
